---
- hosts: all
  gather_facts: true

- hosts: webserver
  serial: 1
  vars_prompt:
    - name: "myapp_version"
      prompt: "Myapp version"
      default: "2"
  become: true
  tasks:
    - name: disable the server in haproxy
      haproxy: 'state=disabled backend=habackend host={{ inventory_hostname }} socket=/var/lib/haproxy/stats'
      delegate_to: "{{ item }}"
      with_items: "{{ groups.lb }}"

    - name: deploy app
      include_role: name=example.app

    - pause: seconds=40

    - name: wait for webserver to come up
      wait_for: port=80 timeout=80

    - name: enable the server in haproxy
      haproxy: 'state=enabled backend=habackend host={{ inventory_hostname }} socket=/var/lib/haproxy/stats'
      delegate_to: "{{ item }}"
      with_items: "{{ groups.lb }}"
